-- Phase 6: Gestión Administrativa SLA + Calendar task source

BEGIN;

-- 1. Expand status CHECK to include new Gestión Administrativa states
ALTER TABLE requests.admin_requests DROP CONSTRAINT IF EXISTS admin_requests_status_check;
ALTER TABLE requests.admin_requests ADD CONSTRAINT admin_requests_status_check
  CHECK (status IN (
    'pending', 'taken', 'in_progress', 'completed',
    'rejected', 'cancelled',
    'under_review', 'approved'   -- keep legacy statuses
  ));

-- 2. SLA tracking
ALTER TABLE requests.admin_requests
  ADD COLUMN IF NOT EXISTS taken_at    TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS taken_by    UUID        NULL REFERENCES users.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS sla_due_at  TIMESTAMPTZ NULL;

-- 3. Task source: 'user' (manual) | 'system' (auto/admin)
ALTER TABLE requests.admin_requests
  ADD COLUMN IF NOT EXISTS task_source VARCHAR(20) NOT NULL DEFAULT 'user';

DO $$
BEGIN
  ALTER TABLE requests.admin_requests
    ADD CONSTRAINT chk_requests_task_source
    CHECK (task_source IN ('user', 'system'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON COLUMN requests.admin_requests.taken_at    IS 'When superadmin took the request — SLA clock starts.';
COMMENT ON COLUMN requests.admin_requests.taken_by    IS 'Superadmin who took the request.';
COMMENT ON COLUMN requests.admin_requests.sla_due_at  IS 'SLA deadline (taken_at + 4 hours).';
COMMENT ON COLUMN requests.admin_requests.task_source IS 'user = created manually; system = auto-generated by role/system.';

COMMIT;
